---
type: Handler
api_version: core/v2 
metadata:
  name: debug
spec:
  type: pipe
  command: >-
    curl -X POST -H "Content-Type: application/json" 
    -H "Authorization: ${SENSU_API_KEY}"
    -d "{
      \"entity\": {
        \"metadata\": {
          \"name\": \"debug\"
        },
        \"entity_class\": \"proxy\"
      },
      \"check\": {
        \"metadata\": {
          \"name\": \"debug\"
        },
        \"output\": \"hello world\"
      },
      \"metadata\": {
        \"labels\": {
          \"foo\": \"bar\"
        }
      }
    }"
    "http://127.0.0.1:8080/api/core/v2/namespaces/default/events/debug/debug"
  timeout: 5
  secrets:
  - name: SENSU_API_KEY
    secret: debug_api_key
---
type: Secret
api_version: secrets/v1
metadata:
  name: debug_api_key
spec:
  provider: vault
  id: secret/sensu/debug#api_key
