---
type: Secret
api_version: secrets/v1
metadata:
  name: influxdb_addr
spec:
  provider: env
  id: SENSU_INFLUXDB_ADDR
---
type: Secret
api_version: secrets/v1
metadata:
  name: influxdb_db
spec:
  provider: env
  id: SENSU_INFLUXDB_DB
---
type: Secret
api_version: secrets/v1
metadata:
  name: influxdb_user
spec:
  provider: env
  id: SENSU_INFLUXDB_USER
---
type: Secret
api_version: secrets/v1
metadata:
  name: influxdb_password
spec:
  provider: env
  id: SENSU_INFLUXDB_PASSWORD
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-influxdb-handler
    io.sensu.bonsai.name: sensu-influxdb-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: ""
    io.sensu.bonsai.tier: Supported
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-influxdb-handler
    io.sensu.bonsai.version: 3.5.0
  name: sensu/sensu-influxdb-handler:3.5.0
spec:
  builds:
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_windows_amd64.tar.gz
      sha512: e08bc38340ceabb759c6b433c83ebf31dd634f1dfd5978762a9a85e91a472a1807cceabf1e27071551a20dee2b8288a469f00a77e07d59e802e0468d9b7e7613
      filters:
        - entity.system.os == 'windows'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_darwin_386.tar.gz
      sha512: afc4eb33c99f682de6651371d3c2da2eddc5503a42ab15f99433facca4068209ece1cceb8d811ca04838bae26e0ef71713d348b7da0f3be6081d412341f6089a
      filters:
        - entity.system.os == 'darwin'
        - entity.system.arch == '386'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_darwin_amd64.tar.gz
      sha512: 13e4b81bfcd5a71077fa5fc5095263ee2a74c94fb22bf20c1c854976484a4eb32c2c927e7f2eb9198284df62271901bcb0ef035409241a3dded4694905599f52
      filters:
        - entity.system.os == 'darwin'
        - entity.system.arch == 'amd64'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_linux_armv7.tar.gz
      sha512: '0851e59107fa7c81ca7638ca044bd3d9488eca0ea5d61a675fe01fd67a97532f0c77eb20b331765420c545b778370f215c7e4b29be03256c579c85ea917f80c8'
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'armv7'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_linux_arm64.tar.gz
      sha512: c7987c3c1fb49bdd4f8a36cae65f843942f97033304b6ed62b02a296bcd9f5724c24dce2b11efcbbd4e830b1e4d0bb6c52b6c75be93ac2bc1e6c11f3aee96c2f
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'arm64'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_linux_386.tar.gz
      sha512: c8c9b63b75a30e4ccc49dc35acd87333fe76aa2bce2a044f31be5df35ca73fb6295ca9e67081322847f1b61d0d7f2355023d404c724490437c9b31c4dbca666b
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == '386'
    - url: https://assets.bonsai.sensu.io/1a919224ac1508c8e0954eebdac0efee57b91e8f/sensu-influxdb-handler_3.5.0_linux_amd64.tar.gz
      sha512: 9ae915d2fd7b264fe02332f0323fbcaae0df187b2629a13eb08cd72a7b16525e949612bfd6c6c79b07278e237cdff165cc51b3aaf70da921cecd2a21bf55a2ec
      filters:
        - entity.system.os == 'linux'
        - entity.system.arch == 'amd64'