---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_token
spec:
  provider: vault
  id: secret/sensu/rocketchat#token
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_userid
spec:
  provider: vault
  id: secret/sensu/rocketchat#id

