---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_token
spec:
  provider: vault
  id: secret/sensu/rocketchat#token
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_userid
spec:
  provider: vault
  id: secret/sensu/rocketchat#id
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_user
spec:
  provider: vault
  id: secret/sensu/rocketchat#user
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_password
spec:
  provider: vault
  id: secret/sensu/rocketchat#password
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_url
spec:
  provider: vault
  id: secret/sensu/rocketchat#url
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_channel
spec:
  provider: vault
  id: secret/sensu/rocketchat#channel
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-rocketchat-handler
    io.sensu.bonsai.name: sensu-rocketchat-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: ""
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-rocketchat-handler
    io.sensu.bonsai.version: 0.1.0
  created_by: sensu
  name: sensu/sensu-rocketchat-handler:0.1.0
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 3d4cba800075b1adb2326ad0bdce8fcd33ecde707e46a535a9090f639e5a1285aba099999439ac740402f1ac9094d1d88b4e1bb74c0ac7b9245b1788c7acc038
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 5ee04dae0e05ac6746de06f5966b28057c011395bdc930b46ae60e1d8168cfb6ef193ace1fd17563f6008cdb320c8aa4f0b59aac820d76cbe24e39aff3140d69
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm'
    - entity.system.arm_version == 6
    headers: null
    sha512: b7800ab1b15e92b35a8154fdd4cfca57086c05f4ce479fd40e2cc6787fbe257645cb889e36863c893a8346edf3afcc4bf6fda6d28d48b01e29b163c990b02c9c
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_linux_armv6.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm'
    - entity.system.arm_version == 7
    headers: null
    sha512: 695c82e4be6a2be6623027a5ef8189b36a615353c0411e5038b6d066e50373811d79172a8c2c71f9fbdcc6975a37aa21b3e77bf63cc3ba163209f9985de7534b
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: fba3f70db5925d59c2664777b88d5f1623ebfd12479406c133d9f5f4323e82b6ed998e751abe14579388412cdaffec981f21a8e2d0fc28e45b74d1010103e9b2
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: ee658b9e362ad3ef3b14e0b3cb889d823b10f390345cc01e02b7b1fb9c4adb321dedc878d3e542d081c16841babb7b3ea1067c53486de5928755b118b0dc12b1
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 9e4337ca406e5aebf164cc6813ef58c2067db012aab8ee17d58f9bd1d464ae566942ce773513872e6fec6b08bc953fcbf72fcae29d45448985c96513d2665f53
    url: https://assets.bonsai.sensu.io/a2299af95a4fa0aed9da508f70262eab4b971b52/sensu-rocketchat-handler_0.1.0_linux_amd64.tar.gz
  filters: null
  headers: null

