---
type: Check
api_version: core/v2
metadata:
  namespace: default
  name: sensu_asset_index_response
  labels:
    aggregate: http_service
spec:
  command: check_http -H sensu-asset-server -N
  runtime_assets:
  - nagios_check_http_v0.1
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: nagios_perfdata
  output_metric_handlers:
  - influxdb
