---
type: GlobalConfig
api_version: web/v1
metadata:
  name: workshop
spec:
  signin_message: Welcome to the **Sensu Go Workshop**!
  always_show_local_cluster: true
  catalog:
    url: "http://homelab:8083"
    release_version: version
