---
version: "3.8"
services:
  # Sensu Backend 
  #
  # Includes embedded database, API, event processor, and web UI). 
  # 
  # See: https://docs.sensu.io/sensu-go/latest/reference/backend/
  sensu-backend:
    image: sensu/sensu:5.21.0
    labels:
    - io.sensu.role=sensu-backend
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    environment:
    - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_TIMESCALEDB_DSN=${SENSU_TIMESCALEDB_DSN}
    volumes:
    - type: volume 
      source: sensu_data
      target: /var/lib/sensu
    command: >-
      sensu-backend start 
      --log-level=debug
      --debug=true

  # Sensu Agent 
  #
  # Includes monitoring agent, local API, and local StatsD socket.
  # 
  # See: https://docs.sensu.io/sensu-go/latest/reference/agent/
  sensu-agent:
    image: sensu/sensu:5.21.0
    labels:
    - io.sensu.role=sensu-agent
    depends_on:
    - sensu-backend
    environment:
    - SENSU_NAMESPACE=default
    command: >-
      sensu-agent start 
      --backend-url=ws://sensu-backend:8081 
      --log-level=info
      --keepalive-interval=5 --deregister=true 
      --detect-cloud-provider
      --subscriptions="linux,demo"
      --labels="foo=bar,bar=baz"

  # Prometheus Push Gateway
  # 
  # Includes the Prometheus Pushgateway for pushing metrics to the Prometheus
  # TSDB.
  # 
  # See: https://github.com/prometheus/pushgateway
  pushgateway:
    image: prom/pushgateway:v1.2.0
    labels:
    - io.sensu.role=tsdb
    depends_on:
    - sensu-agent # not actually true; only used for demo purposes
    ports:
    - 9091:9091
    entrypoint: /bin/pushgateway
    command: >-
      --web.listen-address=":9091"
      --web.telemetry-path="/metrics"
      --web.external-url="http://0.0.0.0:9091"
      --web.route-prefix=""
      --web.enable-lifecycle 
      --web.enable-admin-api 
      --persistence.file="/var/prometheus/pushgateway.store"
      --persistence.interval=5m
      --log.level=info
      --log.format=json

  # Prometheus 
  # 
  # Includes the Prometheus database for storage of telemtry data.
  # 
  # See: https://prometheus.io/docs/introduction/overview/
  prometheus:
    image: prom/prometheus:v2.20.0
    labels:
    - io.sensu.role=tsdb
    depends_on:
    - pushgateway # not actually true; only used for demo purposes
    ports:
    - 9090:9090
    volumes:
    - type: bind
      source: ./config/prometheus
      target: /etc/prometheus
    - type: volume 
      source: prometheus_data
      target: /prometheus
      
  # TimescaleDB  
  #
  # Includes TimescaleDB (Postgres database) for storage of telemetry data.
  # 
  # See: https://docs.timescale.com/latest/introduction
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    labels:
    - io.sensu.role=tsdb
    depends_on:
    - pushgateway # not actually true; only used for demo purposes
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
    - type: bind 
      source: ./config/timescaledb/100-sensu-metrics.sql
      target: /docker-entrypoint-initdb.d/100-sensu-metrics.sql
    - type: volume 
      source: timescaledb_data
      target: /var/lib/postgresql/data
      
  # Grafana 
  #
  # Includes Grafana dashboard and datasource configuration files for 
  # Timescaledb. 
  # 
  # See: https://grafana.com/docs/grafana/latest/
  grafana:
    image: grafana/grafana:7.0.0
    labels:
    - io.sensu.role=dashboards
    depends_on:
    - timescaledb # not actually true; used only for demo purposes
    - prometheus # not actually true; used only for demo purposes
    ports:
    - 3001:3000
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - type: bind
      source: ./config/grafana/provisioning/datasources/ 
      target: /etc/grafana/provisioning/datasources/
    - type: volume 
      source: grafana_data
      target: /var/lib/grafana

volumes:
  sensu_data:
    driver: local
  timescaledb_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
