---
version: "3"
services:
  sensu-backend:
    image: sensu/sensu:5.21.0
    labels:
    - io.sensu.role=sensu-backend
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    environment:
    - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_TIMESCALEDB_DSN=${SENSU_TIMESCALEDB_DSN}
    volumes:
    - "sensu_data:/var/lib/sensu"
    command: >-
      sensu-backend start 
      --log-level=debug
      --debug=true

  sensu-agent:
    image: sensu/sensu:5.21.0
    labels:
    - io.sensu.role=sensu-agent
    depends_on:
    - sensu-backend
    environment:
    - SENSU_NAMESPACE=default
    command: >-
      sensu-agent start 
      --backend-url=ws://sensu-backend:8081 
      --log-level=info
      --keepalive-interval=5 --deregister=true 
      --detect-cloud-provider
      --subscriptions="linux,demo"
      --labels="foo=bar,bar=baz"

  timescaledb-server:
    image: timescale/timescaledb:latest-pg12
    depends_on:
    - sensu-agent # not actually true; only used for demo purposes
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
    - "timescaledb_data:/var/lib/postgresql/data"
    - "./config/timescaledb/003-sensu-metrics.sql:/docker-entrypoint-initdb.d/003-sensu-metrics.sql"
  
  grafana-server:
    image: grafana/grafana:7.0.0
    depends_on:
    - timescaledb-server # not actually true; used only for demo purposes
    ports:
    - 3001:3000
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - "grafana_data:/var/lib/grafana"
    - "./config/grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/"

  # artifactory-server:
  #   image: docker.bintray.io/jfrog/artifactory-oss:latest
  #   depends_on:
  #   - sensu-backend # not actually true; only used for demo purposes
  #   ports:
  #   - 8888:8888
  #   environment:
  #   - SERVER_XML_ARTIFACTORY_PORT=${SERVER_XML_ARTIFACTORY_PORT}
  #   - SERVER_XML_ARTIFACTORY_MAX_THREADS=${SERVER_XML_ARTIFACTORY_MAX_THREADS}
  #   - SERVER_XML_ACCESS_MAX_THREADS=${SERVER_XML_ACCESS_MAX_THREADS}
  #   volumes:
  #   - "artifactory_data:/var/opt/jfrog/artifactory"    

volumes:
  sensu_data:
    driver: local
  timescaledb_data:
    driver: local
  grafana_data:
    driver: local
  # artifactory_data:
  #   driver: local
