---
version: "3.3"
services:
  # Sensu Backend 
  #
  # Includes embedded database, API, event processor, and web UI). 
  # 
  # See: https://docs.sensu.io/sensu-go/latest/reference/backend/
  sensu-backend:
    container_name: sensu-backend
    image: sensu/sensu:${SENSU_BACKEND_VERSION}
    labels:
    - io.sensu.role=sensu-backend
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    environment:
    - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME}
    - SENSU_TIMESCALEDB_DSN=${SENSU_TIMESCALEDB_DSN}
    volumes:
    - type: volume 
      source: sensu_data
      target: /var/lib/sensu
    command: >-
      sensu-backend start 
      --log-level=debug
      --debug=true

  # Prometheus Push Gateway
  # 
  # Includes the Prometheus Pushgateway for pushing metrics to the Prometheus
  # TSDB.
  # 
  # See: https://github.com/prometheus/pushgateway
  pushgateway:
    container_name: pushgateway
    image: prom/pushgateway:${PROM_PUSHGATEWAY_VERSION}
    labels:
    - io.sensu.role=tsdb
    ports:
    - 9091:9091
    entrypoint: /bin/pushgateway
    command: >-
      --web.listen-address=":9091"
      --web.telemetry-path="/metrics"
      --web.external-url="http://0.0.0.0:9091"
      --web.route-prefix=""
      --web.enable-lifecycle 
      --web.enable-admin-api 
      --persistence.file="/var/prometheus/pushgateway.store"
      --persistence.interval=5m
      --log.level=info
      --log.format=json

  # Prometheus 
  # 
  # Includes the Prometheus database for storage of telemtry data.
  # 
  # See: https://prometheus.io/docs/introduction/overview/
  prometheus:
    container_name: prometheus
    image: prom/prometheus:${PROM_PROMETHEUS_VERSION}
    labels:
    - io.sensu.role=tsdb
    ports:
    - 9090:9090
    volumes:
    - type: bind
      source: ./config/prometheus
      target: /etc/prometheus
    - type: volume 
      source: prometheus_data
      target: /prometheus
      
  # TimescaleDB  
  #
  # Includes TimescaleDB (Postgres database) for storage of telemetry data.
  # 
  # See: https://docs.timescale.com/latest/introduction
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:${TIMESCALEDB_VERSION}
    labels:
    - io.sensu.role=tsdb
    ports:
    - 5432:5432
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
    - type: bind 
      source: ./config/timescaledb/100-sensu-metrics.sql
      target: /docker-entrypoint-initdb.d/100-sensu-metrics.sql
    - type: volume 
      source: timescaledb_data
      target: /var/lib/postgresql/data
      
  # Grafana 
  #
  # Includes Grafana dashboard and datasource configuration files for 
  # Timescaledb. 
  # 
  # See: https://grafana.com/docs/grafana/latest/
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    labels:
    - io.sensu.role=dashboards
    ports:
    - 3001:3000
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
    - type: bind
      source: ./config/grafana/provisioning/datasources/ 
      target: /etc/grafana/provisioning/datasources/
    - type: volume 
      source: grafana_data
      target: /var/lib/grafana

  # Sensu Agent 
  #
  # Includes monitoring agent, local API, and local StatsD socket.
  # 
  # See: https://docs.sensu.io/sensu-go/latest/reference/agent/
  sensu-agent:
    container_name: sensu-agent
    image: sensu/sensu:${SENSU_AGENT_VERSION}
    labels:
    - io.sensu.role=sensu-agent
    environment:
    - SENSU_BACKEND_URL=${SENSU_BACKEND_URL}
    - SENSU_NAMESPACE=${SENSU_NAMESPACE}
    - SENSU_SUBSCRIPTIONS=${SENSU_SUBSCRIPTIONS}
    - SENSU_KEEPALIVE_INTERVAL=5
    - SENSU_KEEPALIVE_WARNING_THRESHOLD=10
    - SENSU_KEEPALIVE_CRITICAL_THRESHOLD=20
    command: >-
      sensu-agent start 
      --log-level=info
      --deregister=true 
      --detect-cloud-provider
      --labels="environment=training,workshop_version=${WORKSHOP_VERSION}"

  # Init
  # 
  # Generate workshop configuration files (e.g. user templates)! 
  init-workshop:
    container_name: init-workshop
    build:
      context: docker/init-workshop/
      dockerfile: Dockerfile
    image: init-workshop:latest
    labels:
    - io.sensu.role=init-workshop
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ./.env
      target: /var/lib/sensu/workshop/.env
    - type: bind
      source: ./${COMPOSE_FILE}
      target: /var/lib/sensu/workshop/docker-compose.yaml
    - type: bind
      source: ./docker
      target: /var/lib/sensu/workshop/docker
    - type: bind 
      source: ./scripts
      target: /usr/local/bin
    - type: bind
      source: ./users
      target: /var/lib/sensu/workshop/users
    - type: bind
      source: ./templates
      target: /var/lib/sensu/workshop/templates
      consistency: consistent # required for MacOS
    command: |-
      generate_users
      
volumes:
  sensu_data:
    driver: local
  timescaledb_data:
    driver: local
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
