---
version: "3"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
    - 8086:8086
    volumes:
    - "./data/influxdb:/var/lib/influxdb"
    - "./config/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf"

  influxdb-init:
    build:
      context: "docker/influxdb-init/"
    image: "influxdb-init:latest"
    depends_on:
    - "influxdb"
    command: "curl -i -XPOST http://influxdb:8086/query --data-urlencode 'q=CREATE DATABASE sensu'"

  grafana:
    image: "grafana/grafana:5.1.0"
    ports:
    - 3001:3000
    volumes:
    - "./config/grafana/provisioning/datasources/influxdb.yaml:/etc/grafana/provisioning/datasources/influxdb.yaml"
    - "./config/grafana/provisioning/dashboards/sensu.yaml:/etc/grafana/provisioning/dashboards/sensu.yaml"
    - "./config/grafana/dashboards:/var/lib/grafana/dashboards"

  sensu-backend:
    build:
      context: "docker/sensu-backend/"
      dockerfile: "Dockerfile.debian"
    image: "sensu-backend:latest"
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    volumes:
    - "./config/sensu/backend.yml:/etc/sensu/backend.yml"
    - "./data/sensu/etcd:/var/lib/sensu/etcd"
    labels:
    - "io.sensu.description: The Sensu 2.0 backend"
    - "io.sensu.version: 2.0.0-beta.4.1"
    - "io.sensu.role: backend"
    command: "sensu-backend start"

  sensu-asset-server:
    image: "nginx:latest"
    ports:
    - 8000:80
    volumes:
    - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    - "./assets:/usr/share/nginx/html/assets"

  sensu-agent:
    build:
      context: "docker/sensu-agent/"
      dockerfile: "Dockerfile.debian"
    image: "sensu-agent:latest"
    volumes:
    - "./config/sensu/agent.yml:/etc/sensu/agent.yml"
    depends_on:
    - "sensu-backend"
    labels:
    - "io.sensu.description: The Sensu 2.0 agent"
    - "io.sensu.version: 2.0.0-beta.4.1"
    - "io.sensu.role: agent"
    command: "sensu-agent start --backend-url ws://sensu-backend:8081 --log-level debug"
