---
version: "3.3"
services:
  # Sensu Backend
  #
  # Includes embedded database, API, event processor, and web app.
  #
  # See: https://docs.sensu.io/sensu-go/latest/reference/backend/
  sensu-backend:
    image: sensu/sensu:${SENSU_BACKEND_VERSION}
    labels:
    - io.sensu.role=sensu-backend
    ports:
    - 3000:3000
    - 8080:8080
    - 8081:8081
    healthcheck:
      test: wget -q -O- http://127.0.0.1:8080/health
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
    - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME
    - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD
    - SENSU_INTERNAL_ENVIRONMENT
    - SENSU_WORKSHOP_ENV_SECRET
    volumes:
    - type: volume
      source: sensu_data
      target: /var/lib/sensu
    command: >-
      sensu-backend start
      --log-level=debug
      --debug=true

  # Sensu Agent
  #
  # Includes monitoring agent, local API, and local StatsD socket.
  #
  # See: https://docs.sensu.io/sensu-go/latest/reference/agent/
  sensu-agent:
    image: sensu/sensu:${SENSU_AGENT_VERSION}
    labels:
    - io.sensu.role=sensu-agent
    ports:
    - ${SENSU_API_PORT}/tcp
    - ${SENSU_STATSD_METRICS_PORT}/udp
    healthcheck:
      test: wget -q -O- http://127.0.0.1:3031/healthz
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
    - SENSU_BACKEND_URL
    - SENSU_NAMESPACE
    - SENSU_SUBSCRIPTIONS
    - SENSU_AGENT_PASSWORD
    - SENSU_KEEPALIVE_INTERVAL=5
    - SENSU_KEEPALIVE_WARNING_THRESHOLD=10
    - SENSU_KEEPALIVE_CRITICAL_THRESHOLD=20
    - SENSU_API_HOST
    - SENSU_API_PORT
    - SENSU_STATSD_METRICS_HOST
    - SENSU_STATSD_METRICS_PORT
    command: >-
      sensu-agent start
      --log-level=info
      --deregister=true
      --detect-cloud-provider
      --labels="environment=training,workshop_version=${WORKSHOP_SENSU_VERSION}"
      --statsd-event-handlers timescaledb
      --password ${SENSU_AGENT_PASSWORD:-"P@ssw0rd!"}

  # Elasticsearch
  #
  # Includes Elasticsearch data platform for storage of event and
  # metric data.
  #
  # See:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    labels:
    - io.sensu.role=data-platform
    ports:
    - 9200:9200
    - 9300:9300
    healthcheck:
      test: wget -q -O- http://127.0.0.1:9200/_cluster/health
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
    - "discovery.type=single-node"
    volumes:
    - type: volume
      source: elasticsearch_data
      target: /data

  # Kibana
  #
  # Includes the Kibana web app for operating Elasticsearch and visualizing
  # Elasticsearch data.
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    labels:
    - io.sensu.role=dashboards
    ports:
    - 5601:5601
    healthcheck:
      test: curl -i http://127.0.0.1:5601/api/status
      interval: 10s
      timeout: 5s
      retries: 6
    volumes:
    - type: bind
      source: ./config/elasticsearch/kibana.yml
      target: /usr/share/kibana/config/kibana.yml
    depends_on:
    - elasticsearch

  # Grafana
  #
  # Includes Grafana dashboard and datasource configuration files for
  # InfluxDB, TimescaleDB, and Elasticsarch.
  #
  # See: https://grafana.com/docs/grafana/latest/
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    labels:
    - io.sensu.role=dashboards
    ports:
    - 3001:3000
    healthcheck:
      test: curl -i http://127.0.0.1:3000/api/health
      interval: 10s
      timeout: 5s
      retries: 6
    environment:
    - POSTGRES_PASSWORD
    - GF_AUTH_BASIC_ENABLED
    - GF_SECURITY_ADMIN_USER
    - GF_SECURITY_ADMIN_PASSWORD
    - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
    - type: volume
      source: grafana_data
      target: /var/lib/grafana
    - type: bind
      source: ./config/grafana/provisioning
      target: /etc/grafana/provisioning
    - type: bind
      source: ./config/grafana/dashboards/timescaledb
      target: /etc/grafana/dashboards

  # Vault
  #
  # Includes a Vault "devmode" server for secrets management.
  vault:
    image: vault:${VAULT_VERSION}
    ports:
    - 8200:8200
    environment:
    - VAULT_DEV_ROOT_TOKEN_ID
    - VAULT_DEV_LISTEN_ADDRESS
    healthcheck:
      test: wget -q -O- http://127.0.0.1:8200/v1/sys/health
      interval: 10s
      timeout: 5s
      retries: 6
    command: >-
      vault server -dev -log-level debug

  # Sensu Asset Server
  #
  # Serve Sensu Assets over HTTP using NGINX.
  sensu-assets:
    image: "nginx:latest"
    labels:
    - io.sensu.role=asset-server
    ports:
    - 8000:80
    volumes:
    - type: bind
      source: ./config/nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    - type: volume
      source: asset_data
      target: /usr/share/nginx/html/assets
    healthcheck:
      test: curl -s -I -A "Docker health check (curl)" http://127.0.0.1:80/
      interval: 10s
      timeout: 5s
      retries: 6

  # Sensu Asset SMB Adapter
  #
  # Access the Sensu Assets service via SMB.
  sensu-assets-smb:
    build:
      context: ./docker/sensu-assets/
      dockerfile: Dockerfile.debian
      args:
      - WORKSHOP_PASSWORD
    image: sensu-assets:latest
    labels:
    - io.sensu.role=asset-server
    # user: sensu
    ports:
    - 139:139
    - 445:445
    volumes:
    - type: bind
      source: ./config/samba/smb.conf
      target: /etc/samba/smb.conf
    - type: volume
      source: asset_data
      target: /home/sensu/assets
    healthcheck:
      test: smbstatus --brief
      interval: 10s
      timeout: 5s
      retries: 6
    command: smbd --foreground --log-stdout --configfile /etc/samba/smb.conf

  # Configurator
  #
  # Configuration automation for instructor-led workshops (e.g. user profile
  # generation) using a super light-weight "configuration management" stack:
  #
  # - curl
  # - jq
  # - envsubst (part of the gettext package)
  # - sensuctl
  # - docker & docker-compose
  #
  # See: ./scripts/
  configurator:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
      - SENSU_CLI_VERSION
      - VAULT_VERSION
    image: workshop:${SENSU_CLI_VERSION}
    depends_on:
    - sensu-backend
    labels:
    - io.sensu.role=configurator
    environment:
    - SENSU_BACKEND_CLUSTER_ADMIN_USERNAME
    - SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD
    - VAULT_ADDR
    - VAULT_TOKEN
    - WORKSHOP_HOSTNAME
    - WORKSHOP_SENSU_VERSION
    - WORKSHOP_SENSU_BUILD
    - WORKSHOP_PASSWORD
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ./.env
      target: /workshop/.env
    - type: bind
      source: ./${COMPOSE_FILE}
      target: /workshop/docker-compose.yaml
    - type: bind
      source: ./docker
      target: /workshop/docker
    - type: bind
      source: ./scripts
      target: /usr/local/bin/scripts
    - type: bind
      source: ./users
      target: /workshop/users
    - type: bind
      source: ./config/sensu
      target: /workshop/config/sensu
      consistency: consistent
    - type: bind
      source: ./config/vault
      target: /workshop/config/vault
      consistency: consistent
    - type: volume
      source: sensuctl_data
      target: /root/.config
    command: |-
      seed-workshop-resources

  # Workstation
  #
  # Provide a clean workshop environment based on Alpine Linux w/ sensuctl
  # pre-installed in case the trainee workstation is missing a required
  # dependency.
  #
  # See: https://alpinelinux.org
  sensuctl:
    # container_name: sensuctl
    build:
      context: ./
      dockerfile: Dockerfile
      args:
      - SENSU_CLI_VERSION
      - VAULT_VERSION
    image: workshop:${SENSU_CLI_VERSION}
    labels:
    - io.sensu.role=sensuctl
    environment:
    - SENSU_API_URL
    - SENSU_USERNAME
    - SENSU_PASSWORD
    - SENSU_NAMESPACE
    - VAULT_ADDR
    - VAULT_TOKEN
    working_dir: /root
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ./scripts
      target: /usr/local/bin/scripts
    - type: bind
      source: ./
      target: /root/workshop
      consistency: consistent
    - type: volume
      source: sensuctl_data
      target: /root/.config
      consistency: consistent
    entrypoint: wait-for-sensu-backend sensuctl
    command: >-
      configure -n
      --url ${SENSU_API_URL}
      --username ${SENSU_USERNAME}
      --password ${SENSU_PASSWORD}
      --namespace ${SENSU_NAMESPACE}
      --format tabular

volumes:
  sensuctl_data:
    driver: local
  sensu_data:
    driver: local
  asset_data:
    driver: local
  config_data:
    driver: local
  influxdb_data:
    driver: local
  timescaledb_data:
    driver: local
  elasticsearch_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local