console:
  enabled: true
logging:
  dest: stdout
  timezone: US/Pacific
server:
  name: kibana
  host: 0.0.0.0
  port: 5601
  ssl:
    enabled: false
elasticsearch:
  logQueries: true # default: false
  requestTimeout: 30000
  pingTimeout: 30000
  shardTimeout: 30000
  startupTimeout: 5000
  url: http://elasticsearch:9200
  # username:
  # password:
