global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 30s
  external_labels:
    foo:     bar

scrape_configs:
- job_name: node
  honor_labels: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      source: workshop

- job_name: pushgateway
  honor_labels: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - pushgateway:9091
