---
type: GlobalConfig
api_version: web/v1
metadata:
  name: workshop
spec:
  signin_message: Welcome to the **Sensu Go Workshop Alpha Cluster**!
  always_show_local_cluster: true
  catalog:
    url: "https://catalog.sensu.io"
    release_version: version
