---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: influxdb_metrics
spec:
  command: echo 'web_service value='`echo $RANDOM`' '`date +%s`
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb
