---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: helloworld
spec:
  command: helloworld.rb
  runtime_assets:
  - sensu-ruby_v2.4.4
  - helloworld_v0.1
  publish: true
  interval: 10
  subscriptions:
  - docker
