{
  "type": "Asset",
  "spec": {
    "organization": "default",
    "name": "sensu-ruby-2.4.4",
    "url": "http://sensu-asset-server/assets/sensu-ruby-2.4.4-debian-linux-x86_64.tar.gz",
    "sha512": "a37e528a7e6c4c976ef7bbc68fe06d8cc1c2ac5944452e0a7e7e742b23a555fdc57510875b6f9c351600d203c91b9f1c5e6039c20b563ab598e539bd96a374f3",
    "filters": [
      "System.Platform=='debian'",
      "System.OS=='linux'", 
      "System.Arch=='amd64'"
    ]
  }
}